[rospy.client][INFO] 2012-12-31 16:00:16,578: init_node, name[/autopilot], pid[2803]
[xmlrpc][INFO] 2012-12-31 16:00:16,592: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2012-12-31 16:00:16,594: Started XML-RPC server [http://copter131:60124/]
[rospy.impl.masterslave][INFO] 2012-12-31 16:00:16,595: _ready: http://copter131:60124/
[rospy.init][INFO] 2012-12-31 16:00:16,594: ROS Slave URI: [http://copter131:60124/]
[xmlrpc][INFO] 2012-12-31 16:00:16,596: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2012-12-31 16:00:16,599: Registering with master node http://localhost:11311
[rospy.init][INFO] 2012-12-31 16:00:16,696: registered with master
[rospy.rosout][INFO] 2012-12-31 16:00:16,696: initializing /rosout core topic
[rospy.rosout][INFO] 2012-12-31 16:00:16,759: connected to core topic /rosout
[rospy.simtime][INFO] 2012-12-31 16:00:16,804: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2012-12-31 16:00:16,974: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2012-12-31 16:00:17,042: MAVLinkBridge: Connecting to /dev/ttyACM99 ...
[rosout][INFO] 2012-12-31 16:00:17,060: MAVLinkBridge: Waiting for autopilot heartbeat ...
[rosout][INFO] 2012-12-31 16:00:17,922: MAVLinkBridge: Waiting for usable SYSTEM_TIME ...
[rosout][INFO] 2019-03-27 16:03:54,255: Successfully synced local clock.
[rosout][INFO] 2019-03-27 16:03:54,257: MAVLinkBridge initialized.
[rospy.internal][INFO] 2019-03-27 16:03:54,376: topic[/autopilot/waypoint_goto] adding connection to [http://copter131:46377/], count 0
[rospy.internal][INFO] 2019-03-27 16:03:54,403: topic[/autopilot/heartbeat_onboard] adding connection to [http://copter131:56354/], count 0
[rospy.internal][INFO] 2019-03-27 16:03:54,467: topic[/autopilot/payload_waypoint] adding connection to [http://copter131:56354/], count 0
[rospy.internal][INFO] 2019-03-27 16:03:54,666: topic[/autopilot/acs_pose] adding connection to [/network], count 0
[rospy.internal][INFO] 2019-03-27 16:03:54,672: topic[/autopilot/acs_pose] adding connection to [/constrained_shooter], count 1
[rospy.internal][INFO] 2019-03-27 16:03:54,678: topic[/autopilot/acs_pose] adding connection to [/patrol_box], count 2
[rospy.internal][INFO] 2019-03-27 16:03:54,693: topic[/autopilot/acs_pose] adding connection to [/patrol_box_shooter], count 3
[rospy.internal][INFO] 2019-03-27 16:03:54,696: topic[/autopilot/acs_pose] adding connection to [/safety], count 4
[rospy.internal][INFO] 2019-03-27 16:03:54,698: topic[/autopilot/acs_pose] adding connection to [/red_tracker], count 5
[rospy.internal][INFO] 2019-03-27 16:03:54,699: topic[/autopilot/acs_pose] adding connection to [/swarm_tracker], count 6
[rospy.internal][INFO] 2019-03-27 16:03:54,713: topic[/autopilot/acs_pose] adding connection to [/evader], count 7
[rospy.internal][INFO] 2019-03-27 16:03:54,756: topic[/autopilot/acs_pose] adding connection to [/smart_shooter], count 8
[rospy.internal][INFO] 2019-03-27 16:03:54,807: topic[/autopilot/acs_pose] adding connection to [/tactic_interface], count 9
[rospy.internal][INFO] 2019-03-27 16:03:54,868: topic[/autopilot/acs_pose] adding connection to [/greedy_shooter], count 10
[rospy.internal][INFO] 2019-03-27 16:03:54,886: topic[/autopilot/waypoint_goto] adding connection to [http://copter131:36206/], count 1
[rospy.internal][INFO] 2019-03-27 16:03:54,925: topic[/autopilot/waypoint_goto] adding connection to [http://copter131:52463/], count 2
[rospy.internal][INFO] 2019-03-27 16:03:54,934: topic[/autopilot/waypoint_goto] adding connection to [http://copter131:52463/], count 3
[rospy.internal][INFO] 2019-03-27 16:03:54,934: topic[/autopilot/waypoint_goto] removing connection to http://copter131:52463/
[rospy.internal][WARNING] 2019-03-27 16:03:54,939: Unknown error initiating TCP/IP socket to copter131:37797 (http://copter131:52463/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 618, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][ERROR] 2019-03-27 16:03:54,940: unable to create subscriber transport: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details..  Will try again in 0.5s
[rospy.internal][INFO] 2019-03-27 16:03:54,943: topic[/autopilot/waypoint_goto] adding connection to [http://copter131:51402/], count 3
[rospy.internal][INFO] 2019-03-27 16:03:55,104: topic[/autopilot/acs_pose] adding connection to [/wingman], count 11
[rospy.internal][INFO] 2019-03-27 16:03:55,143: topic[/autopilot/status] adding connection to [/swarm_landing_sequencer], count 0
[rospy.internal][INFO] 2019-03-27 16:03:55,154: topic[/autopilot/status] adding connection to [/task_runner], count 1
[rospy.internal][INFO] 2019-03-27 16:03:55,164: topic[/autopilot/status] adding connection to [/tactic_interface], count 2
[rospy.internal][INFO] 2019-03-27 16:03:55,193: topic[/autopilot/status] adding connection to [/patrol_box], count 3
[rospy.internal][INFO] 2019-03-27 16:03:55,198: topic[/autopilot/status] adding connection to [/linear_formation], count 4
[rospy.internal][INFO] 2019-03-27 16:03:55,207: topic[/autopilot/status] adding connection to [/pn_interceptor], count 5
[rospy.internal][INFO] 2019-03-27 16:03:55,217: topic[/autopilot/status] adding connection to [/swarm_tracker], count 6
[rospy.internal][INFO] 2019-03-27 16:03:55,224: topic[/autopilot/status] adding connection to [/smart_shooter], count 7
[rospy.internal][INFO] 2019-03-27 16:03:55,225: topic[/autopilot/status] adding connection to [/constrained_shooter], count 8
[rospy.internal][INFO] 2019-03-27 16:03:55,227: topic[/autopilot/status] adding connection to [/swarm_control], count 9
[rospy.internal][INFO] 2019-03-27 16:03:55,228: topic[/autopilot/status] adding connection to [/greedy_shooter], count 10
[rospy.internal][INFO] 2019-03-27 16:03:55,246: topic[/autopilot/waypoint_goto] adding connection to [http://copter131:59552/], count 4
[rospy.internal][INFO] 2019-03-27 16:03:55,257: topic[/autopilot/waypoint_goto] adding connection to [http://copter131:48338/], count 5
[rospy.internal][INFO] 2019-03-27 16:03:55,430: topic[/autopilot/mode_num] adding connection to [http://copter131:33119/], count 0
[rospy.internal][INFO] 2019-03-27 16:03:55,435: topic[/autopilot/waypoint_goto] adding connection to [http://copter131:33119/], count 6
[rosout][INFO] 2019-03-27 16:03:55,496: ROS srv recvd: fpr_param_set
[rospy.internal][INFO] 2019-03-27 16:03:55,499: topic[/autopilot/status] adding connection to [/network], count 11
[rospy.internal][INFO] 2019-03-27 16:03:55,533: topic[/autopilot/status] adding connection to [/independent_transit], count 12
[rospy.internal][WARNING] 2019-03-27 16:03:55,945: Unknown error initiating TCP/IP socket to copter131:37797 (http://copter131:52463/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 618, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2019-03-27 16:03:55,945: topic[/autopilot/waypoint_goto] removing connection to http://copter131:52463/
[rospy.internal][ERROR] 2019-03-27 16:03:55,946: unable to create subscriber transport: 'NoneType' object has no attribute 'buff_size'.  Will try again in 1.0s
[rospy.internal][INFO] 2019-03-27 16:03:56,167: topic[/autopilot/status] adding connection to [/wingman], count 13
[rospy.internal][INFO] 2019-03-27 16:03:56,179: topic[/autopilot/status] adding connection to [/evader], count 14
[rospy.internal][INFO] 2019-03-27 16:03:56,182: topic[/autopilot/status] adding connection to [/simple_ground_attack], count 15
[rospy.internal][INFO] 2019-03-27 16:03:56,185: topic[/autopilot/status] adding connection to [/patrol_box_shooter], count 16
[rospy.internal][WARNING] 2019-03-27 16:03:57,953: Unknown error initiating TCP/IP socket to copter131:37797 (http://copter131:52463/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 618, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2019-03-27 16:03:57,954: topic[/autopilot/waypoint_goto] removing connection to http://copter131:52463/
[rospy.internal][ERROR] 2019-03-27 16:03:57,954: unable to create subscriber transport: 'NoneType' object has no attribute 'buff_size'.  Will try again in 2.0s
[rospy.internal][WARNING] 2019-03-27 16:04:01,961: Unknown error initiating TCP/IP socket to copter131:37797 (http://copter131:52463/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 618, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2019-03-27 16:04:01,962: topic[/autopilot/waypoint_goto] removing connection to http://copter131:52463/
[rospy.internal][ERROR] 2019-03-27 16:04:01,963: unable to create subscriber transport: 'NoneType' object has no attribute 'buff_size'.  Will try again in 4.0s
[rosout][INFO] 2019-03-27 16:04:04,920: MAVLink STATUSTEXT: EKF2 IMU1 Origin set to GPS
[rosout][INFO] 2019-03-27 16:04:04,924: MAVLink STATUSTEXT: EKF2 IMU0 Origin set to GPS
[rosout][INFO] 2019-03-27 16:04:05,827: MAVLink STATUSTEXT: EKF2 IMU0 is using GPS
[rosout][INFO] 2019-03-27 16:04:05,831: MAVLink STATUSTEXT: EKF2 IMU1 is using GPS
[rospy.internal][WARNING] 2019-03-27 16:04:09,979: Unknown error initiating TCP/IP socket to copter131:37797 (http://copter131:52463/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 618, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2019-03-27 16:04:09,981: topic[/autopilot/waypoint_goto] removing connection to http://copter131:52463/
[rospy.internal][ERROR] 2019-03-27 16:04:09,985: unable to create subscriber transport: 'NoneType' object has no attribute 'buff_size'.  Will try again in 8.0s
[rospy.internal][WARNING] 2019-03-27 16:04:26,010: Unknown error initiating TCP/IP socket to copter131:37797 (http://copter131:52463/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 618, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2019-03-27 16:04:26,012: topic[/autopilot/waypoint_goto] removing connection to http://copter131:52463/
[rospy.internal][ERROR] 2019-03-27 16:04:26,013: unable to create subscriber transport: 'NoneType' object has no attribute 'buff_size'.  Will try again in 16.0s
[rospy.internal][WARNING] 2019-03-27 16:04:58,056: Unknown error initiating TCP/IP socket to copter131:37797 (http://copter131:52463/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 618, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2019-03-27 16:04:58,057: topic[/autopilot/waypoint_goto] removing connection to http://copter131:52463/
[rospy.internal][ERROR] 2019-03-27 16:04:58,058: unable to create subscriber transport: 'NoneType' object has no attribute 'buff_size'.  Will try again in 32.0s
[rospy.internal][WARNING] 2019-03-27 16:06:02,130: Unknown error initiating TCP/IP socket to copter131:37797 (http://copter131:52463/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 618, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2019-03-27 16:06:02,131: topic[/autopilot/waypoint_goto] removing connection to http://copter131:52463/
[rospy.internal][ERROR] 2019-03-27 16:06:02,132: unable to create subscriber transport: 'NoneType' object has no attribute 'buff_size'.  Will try again in 64.0s
[rospy.internal][INFO] 2019-03-27 16:06:17,554: topic[/autopilot/heartbeat_ground] adding connection to [http://copter131:39816/], count 0
[rosout][INFO] 2019-03-27 16:06:55,988: ROS srv recvd: fpr_param_setlist
[rosout][INFO] 2019-03-27 16:06:56,028: MAVLink STATUSTEXT: APM:Copter V3.5-dev (f3195c7e)
[rosout][INFO] 2019-03-27 16:06:56,032: MAVLink STATUSTEXT: PX4: 3df5644c NuttX: be6ff61a
[rosout][INFO] 2019-03-27 16:06:56,045: MAVLink STATUSTEXT: Frame: QUAD
[rosout][INFO] 2019-03-27 16:06:56,047: MAVLink STATUSTEXT: PX4v2 003E0023 31355103 33333832
[rosout][INFO] 2019-03-27 16:06:57,377: ROS srv recvd: slave_setup
[rosout][WARNING] 2019-03-27 16:07:00,001: PARAM ALT_HOLD_RTL doesn't exist
[rosout][INFO] 2019-03-27 16:07:00,020: ROS srv recvd: load_rally
[rosout][INFO] 2019-03-27 16:07:00,033: ROS srv recvd: fpr_rally_setall
[rospy.internal][INFO] 2019-03-27 16:07:02,394: topic[/autopilot/mode_num] adding connection to [http://copter131:39816/], count 1
[rosout][INFO] 2019-03-27 16:07:02,397: Mode settings are for plane.
[rosout][INFO] 2019-03-27 16:07:02,398: Sent mode MANUAL (0) to autopilot 
[rosout][INFO] 2019-03-27 16:07:02,399: ROS sub recvd: mode_num
[rosout][INFO] 2019-03-27 16:07:05,265: Mode settings are for plane.
[rosout][INFO] 2019-03-27 16:07:05,267: Sent mode MANUAL (0) to autopilot 
[rosout][INFO] 2019-03-27 16:07:05,270: ROS sub recvd: mode_num
[rospy.internal][INFO] 2019-03-27 16:07:06,112: topic[/autopilot/arm] adding connection to [http://copter131:39816/], count 0
[rosout][INFO] 2019-03-27 16:07:06,116: ROS sub recvd: arm
[rosout][INFO] 2019-03-27 16:07:06,247: ROS srv recvd: load_wp
[rosout][INFO] 2019-03-27 16:07:06,261: ROS srv recvd: wp_setall
[rosout][INFO] 2019-03-27 16:07:07,834: MAVLink STATUSTEXT: Flight plan received
[rospy.internal][INFO] 2019-03-27 16:07:07,983: topic[/autopilot/waypoint_goto] adding connection to [http://copter131:39816/], count 7
[rosout][INFO] 2019-03-27 16:07:07,993: ROS sub recvd: waypoint_goto
[rosout][INFO] 2019-03-27 16:07:08,152: ROS srv recvd: wp_getrange
[rosout][INFO] 2019-03-27 16:07:09,232: Mode settings are for copter.
[rosout][INFO] 2019-03-27 16:07:09,234: Sent mode GUIDED (4) to autopilot 
[rosout][INFO] 2019-03-27 16:07:09,236: ROS sub recvd: mode_num
[rosout][INFO] 2019-03-27 16:07:09,748: Mode settings are for copter.
[rosout][INFO] 2019-03-27 16:07:09,750: Sent mode GUIDED (4) to autopilot 
[rosout][INFO] 2019-03-27 16:07:09,753: ROS sub recvd: mode_num
[rosout][INFO] 2019-03-27 16:07:10,215: Mode settings are for copter.
[rosout][INFO] 2019-03-27 16:07:10,217: Sent mode GUIDED (4) to autopilot 
[rosout][INFO] 2019-03-27 16:07:10,219: ROS sub recvd: mode_num
[rosout][INFO] 2019-03-27 16:07:10,737: Mode settings are for copter.
[rosout][INFO] 2019-03-27 16:07:10,740: Sent mode GUIDED (4) to autopilot 
[rosout][INFO] 2019-03-27 16:07:10,741: ROS sub recvd: mode_num
[rospy.internal][INFO] 2019-03-27 16:07:11,248: topic[/autopilot/copter_takeoff] adding connection to [http://copter131:39816/], count 0
[rosout][INFO] 2019-03-27 16:07:11,255: ROS sub recvd: copter_takeoff
[rosout][INFO] 2019-03-27 16:07:16,254: Mode settings are for copter.
[rosout][INFO] 2019-03-27 16:07:16,257: Sent mode AUTO (3) to autopilot 
[rosout][INFO] 2019-03-27 16:07:16,262: ROS sub recvd: mode_num
[rosout][INFO] 2019-03-27 16:07:18,168: ROS sub recvd: waypoint_goto
[rosout][INFO] 2019-03-27 16:07:19,163: ROS srv recvd: wp_getrange
[rosout][INFO] 2019-03-27 16:07:26,421: ROS srv recvd: wp_getlast
[rosout][INFO] 2019-03-27 16:07:27,621: ROS srv recvd: wp_getlast
[rosout][INFO] 2019-03-27 16:07:27,888: ROS sub recvd: waypoint_goto
[rosout][INFO] 2019-03-27 16:07:28,210: ROS srv recvd: wp_getrange
[rosout][INFO] 2019-03-27 16:08:10,135: Mode settings are for copter.
[rosout][INFO] 2019-03-27 16:08:10,138: Sent mode STABILIZE (0) to autopilot 
[rosout][INFO] 2019-03-27 16:08:10,139: ROS sub recvd: mode_num
[rospy.internal][WARNING] 2019-03-27 16:08:10,245: Unknown error initiating TCP/IP socket to copter131:37797 (http://copter131:52463/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 618, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2019-03-27 16:08:10,246: topic[/autopilot/waypoint_goto] removing connection to http://copter131:52463/
[rospy.internal][ERROR] 2019-03-27 16:08:10,246: unable to create subscriber transport: 'NoneType' object has no attribute 'buff_size'.  Will try again in 128.0s
[rosout][INFO] 2019-03-27 16:08:12,549: ROS sub recvd: arm
[rosout][INFO] 2019-03-27 16:08:12,947: ROS srv recvd: wp_getrange
